### PR TITLE
Fix/UI style home

### PR DESCRIPTION
**Pull request by mercuryeater**
This is the PR for the issue regarding the "**_Correction for Home's content width #27_**"
I used flex for centering the components in home.
Added full width and max width property to some components.

I think the contributing.md appears modified because the line endings, It would be nice to add an editorconfig file to maintain compatibility. 

**Change:**
image

### CODE REVIEW

**Comment by hellofaizan** [comment]
@mercuryeater can you fix the responsive UI of this section

**Comment by mercuryeater** [comment]
Off course, I'll send it tomorrow same hour.

**Comment by hellofaizan** [comment]
@mercuryeater Any Progress?

**Comment by mercuryeater** [comment]
I had a rough weekend but today I'm going to send another PR 😁

**Comment by hellofaizan** [comment]
No issues👍
@mercuryeater

**Comment by mercuryeater** [comment]
Hey @hellofaizan 🖐 
I just sent a couple commits with new changes to the Home page, I would say the responsive it's much better.

**Comment by hellofaizan** [comment]
Awesome 👍

**Pull request merged**
