### PR TITLE
Created contribution.md

### PR DESCRIPTION
**Pull request by darksuei**
This repository lacks a contribution.md file inline with [hacktoberfest contribution guidelines](https://hacktoberfest.com/participation/#maintainers). 
Do let me know if I missed anything.

### CODE REVIEW

**Comment by hellofaizan** [comment]
@darksuei You

**Comment by hellofaizan** [comment]
@darksuei you created the `hactoberfest-setup` branch from `main` branch, but our main branch has failed deployment. Currently active branch is `dev`. Commit to that

**Review by hellofaizan — APPROVED** [review]
👍

**Comment by hellofaizan** [comment]
@darksuei you up for contributing to XProfile?? We currently working on user Dashboard page and we need help

If yes, message me on Discord https://discord.gg/vUHMxPvege

**Comment by darksuei** [comment]
Yes, I am! But I'm currently swamped with tasks at this point. 
However if there's minor tasks, you can create issues and ping me ill try my best @hellofaizan

**Pull request merged**
